export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const HANDLE_CHANGE = 'HANDLE_CHANGE';
export const CLEAR_VALUES = 'CLEAR_VALUES';

export const CREATE_JOB_BEGIN = 'CREATE_JOB_BEGIN';
export const CREATE_JOB_SUCESS = 'CREATE_JOB_SUCESS';
export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR';

export const GET_JOB_SUCESS = 'GET_JOB_SUCESS';
export const GET_JOB_BEGIN = 'GET_JOB_BEGIN';
export const SET_EDIT_JOB = 'SET_EDIT_JOB';

export const DISPLAY_MODAL = 'DISPLAY_MODAL';   
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const DELETE_JOB_BEGIN = 'DELETE_JOB_BEGIN';

export const EDIT_JOB_BEGIN = 'EDIT_JOB_BEGIN';
export const EDIT_JOB_SUCESS = 'EDIT_JOB_SUCESS';
export const EDIT_JOB_ERROR = 'EDIT_JOB_ERROR';

export const DELETE_JOB_ERROR = 'DELETE_JOB_ERROR';
